"""A Python Pulumi program"""

import pulumi
import pulumi_kubernetes as k8s
import pulumi_digitalocean as do

from utils import getKubeconfig

config = pulumi.Config()

# Define a digital ocean cluster
cluster = do.KubernetesCluster(
    "brice-demo-cluster",
    node_pool={
        "name": "worker-pool",
        "node_count": 2,
        "size": "s-1vcpu-2gb",
    },
    region="lon1",
    version="1.19.3-do.2"
)

# Extract kubeconfig and export it
# We have to do special things to handle DO's 7 day token rotation
kubeconfig = getKubeconfig(cluster, "admin", config.require_secret("DIGITALOCEAN_KUBERNETES_TOKEN"))
pulumi.export("kubeconfig", kubeconfig)

# Extract and export the kubeconfig on generated by the cluster creation
k8sprovider = k8s.Provider("do-k8s", kubeconfig=kubeconfig)
pulumi.export("pulumi-kubeconfig", cluster.kube_configs[0]["rawConfig"])



# k8s_opts = pulumi.ResourceOptions(provider=k8sprovider)



